travis:
  secure:
    BINSTAR_TOKEN: YUd9Eukp+KFv6U6AgOgxhD500Flnsl/elxTWkQU0tVP5r0jv9c7u/nbDVZYKM8xKxkW7n8SSW2g4YP+qaa8JB5Y9qx8XO629ySd0taSdsjGAHH924mK7hYslqgANIX6l6KE4ayIunFgvbJ6gX/w5TrNKCkiHET17JzYSOwbSlJ8q0g70pEM7CiEdnAsRiIRSchO+LWttludSnfbuy+PKpR4HBMr+5epPxWX0pVhvw8V+iiukuDrOyGFZL3+DXgP7SAbUZo0uFabwpfzqLGwSgXucvaBfHuaGa8qRyYr04+Phh5RP5Egf0ajwjeH0G61nu3GCQMObzBaEmMgqNBdKbx6FFJewuSREZN+lp09T3fnT5krcHXNc7Mte97ur5GqEqKUS5PlONGX/q/eKgJQ5uP9ajPcwKqmdduIO9WmCt2evJGlHMarFyUb7Q0J35GEBYd8fhjmh/+aXCYsrp8G/KjalMgbHAxtewlaZ4d6t0tvXRoJMYnkOHFFGcbtvgJhxWTkj4oA5ufk74xugqPWWe0oZTBDD4HfPxUz0TafZkKWxZama2YyucEF23XNk2hBguD2eJLgtwI1RlN625x3xxm5+DtaahYwMPM+DEEsB9YLOIoHy8d96yAmfAcxky4kaojKJgl7r3fVrQ7C0DwOUkLhUBepAn+fSKak/MqfQRsI=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
