travis:
  secure:
    BINSTAR_TOKEN: p0wvmNrLG7QJy2vL9X5+yVG9Gv79hEMZrryZ/Y94dDZrSBKLsVHtGE1RfHnK4ONg1vxzZtHEwQuTs6Rd95ElQrLgi8CUISWbWj+UorkOfoGQxO3usaaErXVt+UobEq4XXi3aZZ7KNVYuyCs9zDgWOOf70NuAqqJb+IyUbc/6auPPCHBEUj73mBIW2Ai48phFwaKgvtxY29zH90QotOOK4iSCdcKIIdcGEHA0msiuiepuDssQ+3I/XJa0ttRsQt6t74r9mop9P6UuLrKqdAsWMIK05wweqlKFQ9sXAWJ8flhZcqUtV2ODrYekYgIDbPGKTN/i1VHMGU/J8EWAXt4OmclqPOx1gioFg6yHYdOeU9HzKd8SmhT1wmmuw6JR6HkDe6VU0kL4opLQP1nuV4GeI7EqWXs73SbXfbl+lloUcMvlQeFQC3HEH6B1L67ACCfpkEnnm5UK1Qjue2GIbtpI6IxYT0e2FebE11POdqdQJ8GvyPYGudoTGblZIWiT/z+vIPR4N39BGIKQLnwRXTagFWEx7dG9QP7XeWR2XJ/JlmkU2FSVODvjSeVCgNSpbqEwXEn2ma/28Lf169RNKyiTT638p1y5g4SvPiUqz1svfa8zF1BBoVJlnVwI7qUuKjfcMXa1QBfmcj4VGbb9wfy0cFQAPGYHbNyHzqwAGJPaLHE=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
